### ISSUE TITLE
Remaining Edits from IPDS

### ISSUE THREAD

**Issue by ellenbechtel** [USGS-VIZLAB/snow-to-flow#102]
### Reviewers were: 

- Julia Prokopec, WIM
- David Selkowitz, Nevada Water Science Center

### Edits Requested:

- [x] add a sidebar expander that explains "Water Year" somewhere. [ EB drafted one, it's in this PR]
- [x] JS wants us to choose "flow" or "streamflow" and be consistent. I suggest "flow" because it's in the title, but am not married to the decision.
- [x] DS wants to add this in the Sublimation sidebar: "Higher wind speeds can accelerate sublimation, and sublimation losses are much more significant in the more continental areas (Colorado, Wyoming) and less significant in the more coastal mountains."
- [x] JP requests that we put more consistent/clear titles on each of our charts, especially the line chart/ridgeplots which have none.
- [x] DS wants to add this to the last paragraph: 

> My only other recommendation is to mention that the USGS contribution to snow science also includes the development and production of the Landsat snow covered area product, which is available through Earth Explorer. Additional information can be found here.  https://www.usgs.gov/core-science-systems/nli/landsat/landsat-fractional-snow-covered-area

### Other:

- [x] On some smaller screens, one cloud image in the splash gets cut off with a hard line. Adjust image sizing to remove that. [EB did this, it's in her branch that hasn't been PR'ed yet as of 4/16]
- [x] Need to adjust caption overlay sizing, it sometimes covers up important parts of the diagrams. [EB did a version of this as of 4/19]
- [x] update diagram labels with correct terminology (SWE instead of "snowpack thickness") [ EB did this, it's on test but not on -beta]
- [x] Decide on a citation/linking style and implement it
- [x] move citation in first line down to the rest of the paragraph.
- [x] Add a link to download the diagrams
- [ ] Update the README.md with final repo description and instructions for accessing data? [ EB is interested, re: conversation at kickoff with JR ]
- [x] Add units to buttons, not to axes
- [x] On mobile, buttons aren't behaving well in regards to size.  CN has already done some work on their branch on this, but just want to flag it. 
![image](https://user-images.githubusercontent.com/25129074/115067344-c621a280-9ebe-11eb-80a1-8ae825726584.png)

**Comment by collnell** [comment]
I think the buttons should be different now based on PRs that have already been made. Have you pulled down recently?
