### ISSUE TITLE
Make a <References /> template

### ISSUE THREAD

**Issue by ellenbechtel** [USGS-VIZLAB/snow-to-flow#11]
We need some sort of template for a "References" section to this (and future) viz.  We've seen it done a few different ways, and don't have super strong preferences as to one way or the other.  

Which style do you think would work best for future vizzies?  We want to have a section to compile USGS science citations since scientists who read our stuff will expect it. But we also want it to be more easily usable and digestable than typical bibliographies.  What do you think?

### For Example: 

Gages, "bibliography" style
![image](https://user-images.githubusercontent.com/25129074/107823786-5f60fb00-6d4e-11eb-9348-69d90ae514bd.png)

Gages, "accordion" style
![image](https://user-images.githubusercontent.com/25129074/107823815-6ab42680-6d4e-11eb-877c-aa53e8906c00.png)

Fire-Hydro, "bullet list" style
![image](https://user-images.githubusercontent.com/25129074/107823858-7f90ba00-6d4e-11eb-922c-08567d906a45.png)

**Comment by mwernimont** [comment]
![Screen Shot 2021-02-22 at 10 13 23 AM](https://user-images.githubusercontent.com/6390096/108735888-a8efd980-74f6-11eb-8612-7c0b66a08489.png)
![Screen Shot 2021-02-22 at 10 13 29 AM](https://user-images.githubusercontent.com/6390096/108735889-a8efd980-74f6-11eb-8e10-e8633b2c27f7.png)

**Comment by mwernimont** [comment]
PR: https://github.com/USGS-VIZLAB/snow-to-flow/pull/27
