### ISSUE TITLE
Make a <Sidebar /> component

### ISSUE THREAD

**Issue by ellenbechtel** [USGS-VIZLAB/snow-to-flow#13]
We are trying to keep our text really tight and to-the-point.  But, there will be moments when we mention something like "SWE" and a user will ask "What's SWE?" We want to give them the option to see a sidebar to read more while still in the page.  "Sidebar" doesn't necessarily have to mean that it's on the side of the page - just that it's a separate section to answer a question that the user might have while digesting the content.

There's a version of this in Temp-Prediction, where we have a [matrix-explainer-container set to "hidden"](https://github.com/usgs-makerspace/temperature-prediction/blob/a5d6cf4add327a3cc8327e2db1b1361b8a513cdf/src/views/set2/Set2.vue#L84) by default, and then a [little script that toggles the class](https://github.com/usgs-makerspace/temperature-prediction/blob/a5d6cf4add327a3cc8327e2db1b1361b8a513cdf/src/views/set2/Set2.vue#L2164) to let the div appear when the user wants it.  Fair warning - this is my attempt at going from js to Vue and it's not super efficient, I bet!!

We're open to lots of different iterations of making this work.  But in our heads, the wireframe would work something like this: 

![image](https://user-images.githubusercontent.com/25129074/107825169-a7811d00-6d50-11eb-9b78-698c41028bc3.png)

We can work on a wireframe for mobile too, but it's almost the end of the day here!

The important features would be:

- The transition between the "collapsed" and "expanded" states should be nice, not super jerky
- The user has the option to collapse the sidebar again

**Comment by mwernimont** [comment]
Component usage:
`<Sidebar>
        <template v-slot:sidebarTitle>
          Add Custom Button Title
        </template>
        <template v-slot:sidebarMessage>
          Add Custom Side Bar Message Here
        </template>
      </Sidebar>`

**Comment by mwernimont** [comment]
![sidebar](https://user-images.githubusercontent.com/6390096/108552907-8fad1a00-72b7-11eb-8c5f-1fc034dd8741.gif)

**Comment by mwernimont** [comment]
PR: https://github.com/USGS-VIZLAB/snow-to-flow/pull/25
