### ISSUE TITLE
Update URL to DOI-USGS

### ISSUE THREAD

**Issue by padilla410** [USGS-VIZLAB/snow-to-flow#141]
These lines will need an update to DGEC: `https://github.com/DOI-USGS/`

https://github.com/USGS-VIZLAB/snow-to-flow/blob/9175f321f3c0663dbd8636e7569ae0a1c02d4983/code.json#L17-L20

**Comment by padilla410** [comment]
[here](https://github.com/USGS-VIZLAB/snow-to-flow/blob/main/code.json#L13) too

**Comment by aaarcher-usgs** [comment]
Also mentioned in issue #140
