### ISSUE TITLE
Update labor hours

### ISSUE THREAD

**Issue by padilla410** [USGS-VIZLAB/snow-to-flow#142]
I don't think this number needs to be precise, but 40 hours seems too low. There are >700 commits in the repo. Maybe 100-200? I don't have a good sense of viz development time.

https://github.com/USGS-VIZLAB/snow-to-flow/blob/9175f321f3c0663dbd8636e7569ae0a1c02d4983/code.json#L22

**Comment by aaarcher-usgs** [comment]
Updated to estimated 300 hours.
