### ISSUE TITLE
lazy load on refresh

### ISSUE THREAD

**Issue by collnell** [USGS-VIZLAB/snow-to-flow#65]
The lazy loading doesn't seem to work if you refresh the page halfway down. The placeholder image just stays 

![image](https://user-images.githubusercontent.com/17803537/112007713-e2663580-8af2-11eb-87e0-14d0a27a60d0.png)

**Comment by mwernimont** [comment]
My initial thought is its probably the lint on save reload where it doesn't work properly, which GSAP also seems to have issues.  If that is the case a user would never experience that as they wouldn't be developing on our viz and be getting lint reloads.  But if it is a full refresh issue I will solve this.

**Comment by mwernimont** [comment]
And it is a full refresh issue.  Digging in!

**Comment by mwernimont** [comment]
Lazy loading now recognizes when an image is loaded into the viewport
https://user-images.githubusercontent.com/6390096/112025439-28c39080-8b03-11eb-96b1-1f1e003aa0ec.mp4

**Comment by mwernimont** [comment]
PR: https://github.com/USGS-VIZLAB/snow-to-flow/pull/66
