### ISSUE TITLE
Make a component that can house and auto-play an mp4

### ISSUE THREAD

**Issue by ellenbechtel** [USGS-VIZLAB/snow-to-flow#7]
John Hammond has a bunch of drone videos ([here's the folder of them in sharepoint](https://teams.microsoft.com/_#/files/Function%20-%20Vizlab?threadId=19%3A2e541bec4bb04602bf45506b96b4a621%40thread.skype&ctx=channel&context=drone_vids_and_timelapses&rootfolder=%252Fsites%252FIIDDStaff%252FShared%2520Documents%252FFunction%2520-%2520Vizlab%252FVisualizations%252FSnowmelt%252F0_Inspiration%252Fdrone_vids_and_timelapses)) of rivers in snow that are AWESOME.  We want to be able to play some of the videos in the page.  Here are some thoughts:

- We're not sure yet if it'll a full-width element (like a section break) or just one part of a figure (like a photo to break up descriptive text). But if we can have a reusable component that loads in a video, then be able to insert that component into a div that sizes/crops the video to the width of the parent div, then we're golden. 

- No preference about whether the video plays on a loop, or auto-plays only when viewer is viewing it.  Happy to go with whatever is most efficient to build, or whichever requires the least processing power.

![image](https://user-images.githubusercontent.com/25129074/107821903-3f7c0800-6d4b-11eb-8b16-3e9d93e9ed32.png)

**Comment by collnell** [comment]
This component is `Video` and exists in the base template  now
