### ISSUE TITLE
Add Caption capability to Lightbox in the Carousels

### ISSUE THREAD

**Issue by ellenbechtel** [USGS-VIZLAB/snow-to-flow#75]
So in the current setup, there are four components with carousels.

1. [Diagrams for a normal snow year](https://github.com/USGS-VIZLAB/snow-to-flow/blob/main/src/components/DiagramCarouselNormal.vue)
2. [Diagrams for a "high snow" year](https://github.com/USGS-VIZLAB/snow-to-flow/blob/main/src/components/DiagramCarouselHigh.vue )
3. [Diagrams for  "low snow" year](https://github.com/USGS-VIZLAB/snow-to-flow/blob/main/src/components/DiagramCarouselLow.vue)
4. [Images of USGS employees measuring SWE at SNOTEL sites](https://github.com/USGS-VIZLAB/snow-to-flow/blob/main/src/components/ImgCarousel.vue)

The way these are set up, they use a combination of [vue-carousel](https://ssense.github.io/vue-carousel/) for the carousel and slide features, and [v-img](https://github.com/crowdbotics/v-img) for the lightbox feature that allows each image to be clicked on to open up a gallery of similar images.

I've tried a number of ways of getting captions to appear in gallery/lightbox mode when a clicked-on image goes full screen, but I can't figure it out.  It'd be nice to have the ability to put captions below the image when it's full screen, likely over an opacity overlay or something so it stands out over the image.  But I can't figure out how to do it!  Could you help?

Here's a screenshot of what it looks like currently: there's definitely an overlay at the top where the 6/9 and the "x" go, but I can't figure out how to get one on the bottom. 
![image](https://user-images.githubusercontent.com/25129074/112862338-ab0fff80-9083-11eb-8fb0-af5de1436d92.png)

When it's like this, I notice in the code that it adds a new div with class "fullscreen-v-img" that has a div called "header-v-img" for the overlay on top. I can't remember exactly what I tried to be able to access some built-in "footer-v-img" that I had a suspicion existed, but alas!  I was thwarted.  I think you might have better skills to be able to figure it out! 
![image](https://user-images.githubusercontent.com/25129074/112862586-edd1d780-9083-11eb-87ae-786cc688f387.png)

**Comment by ellenbechtel** [comment]
Ooop!  I noticed a new quirk. When you click on an image, the div appears WONDERFULLY. But then as you use arrow keys to go left or right, the caption stays the same.

If you click out of the lightbox and back in to a new image, the caption is correct.  So it must be something like not running the function on left/right arrow key hits, only on clicks. Weird!

(I'm working on getting a gif, but it's coming out at 50MB which is very strange. So a written description is all i've got for now!)

**Comment by mwernimont** [comment]
PR: https://github.com/USGS-VIZLAB/snow-to-flow/pull/89

**Comment by ellenbechtel** [comment]
Quirk is fixed, yay! Closing this.
