### ISSUE TITLE
mobile sizing

### ISSUE THREAD

**Issue by collnell** [USGS-VIZLAB/snow-to-flow#81]
@mwernimont any of these you can address would be a big help!
- [x] The ridge button panel needs to be adjusted 
- [x] Line chart is cut off
- [x] The subtitles are bigger than the section title on mobile
- [x] Long subtitles take up most of the screen
- [x] Diagrams are too small to read on mobile

I noticed a few sizing things on mobile safari:

1.  The ridge button panel needs to be adjusted 
![File_0002](https://user-images.githubusercontent.com/17803537/113182681-cbbd8e00-9218-11eb-9f96-7975541477ea.png)

2.  line chart is cut off
![File_0003](https://user-images.githubusercontent.com/17803537/113182758-e42da880-9218-11eb-9489-aad2f56e78a3.png)

3.  the subtitles are bigger than the section title on mobile
![File_000](https://user-images.githubusercontent.com/17803537/113182804-f1e32e00-9218-11eb-8d8c-7d0063d10c86.png)

4.  long subtitles take up most of the screen - reduce in size and try to shorten and sweeten the wording
![File_0001](https://user-images.githubusercontent.com/17803537/113182959-1808ce00-9219-11eb-9662-4f7094dfcc1c.png)

5. diagrams are too small to read on mobile. they expand singly so this isn't a huge issue IMO but worth thinking about
![File_0004](https://user-images.githubusercontent.com/17803537/113183017-2d7df800-9219-11eb-8e11-12880537401d.png)

**Comment by mwernimont** [comment]
Working on - The subtitles are bigger than the section title on mobile

**Comment by mwernimont** [comment]
@collnell still too big?

![Screenshot_20210331-132338](https://user-images.githubusercontent.com/6390096/113192484-6d96a800-9224-11eb-98d3-a45ccbabab70.png)

**Comment by collnell** [comment]
To me this looks like they are almost the same size but the section title is still slightly smaller. The same size or bigger section title makes sense to me. But, the overall size of the section title (over the image) seems appropriate. Maybe reduce the subtitles to be a little bit smaller?

**Comment by mwernimont** [comment]
Working on: The ridge button panel needs to be adjusted.
